### ISSUE TITLE
gplus.py

### ISSUE THREAD

**Issue by MrEmielH** [aa755/home-assistant#2]
Make sure you are running the latest version of Home Assistant before reporting an issue.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum:

**Home Assistant release (`hass --version`):**

0.41

**Component/platform:**

gplus.py

**Description of problem:**

No device tracker is added and the following lines are shown in the log.

17-04-18 21:59:30 ERROR (Thread-5) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/device_tracker/gplus.py", line 95, in get_position
    update_data_at()
  File "/config/custom_components/device_tracker/gplus.py", line 90, in update_data_at
    data['at'] = sdict['SNlM0e']
KeyError: 'SNlM0e'
17-04-18 22:01:30 ERROR (Thread-5) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/device_tracker/gplus.py", line 95, in get_position
    update_data_at()
  File "/config/custom_components/device_tracker/gplus.py", line 90, in update_data_at
    data['at'] = sdict['SNlM0e']
KeyError: 'SNlM0e'

**Expected:**

A new device Tracker is added

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**

```yaml

device_tracker:
   - platform: owntracks
     max_gps_accuracy: 200
     waypoints: True
     waypoint_whitelist:
       - emiel
   - platform: gplus
     id: Emiel_Android
     url: https://www.googleapis.com/plus/v1/people/{idDummy}?key={api-key linked to dummy}
     cookie_sid: {cookie_sid}
     cookie_hsid: {cookie_hsid}
     cookie_ssid: {cookie_ssid}
     data_freq: 15
     home_url: https://plus.google.com/{idMain}


```
