### ISSUE TITLE
Google didn't send the location

### ISSUE THREAD

**Issue by MrEmielH** [aa755/home-assistant#3]
Make sure you are running the latest version of Home Assistant before reporting an issue.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum:

**Home Assistant release (`hass --version`):**

0.42.4

**Python release (`python3 --version`):**

Python 3.5.3

**Component/platform:**

gplus.py

**Description of problem:**

Google refuses to send location, the following lines keep coming up in the log every time Home-Assistant tries to get my location.

> 17-04-19 14:15:04 ERROR (Thread-12) [custom_components.device_tracker.gplus] No response received to the location query
17-04-19 14:15:04 ERROR (Thread-12) [custom_components.device_tracker.gplus] Google didn't send the location. Updating data['at']

> 17-04-19 14:20:00 ERROR (Thread-12) [custom_components.device_tracker.gplus] No response received to the location query
17-04-19 14:20:00 ERROR (Thread-12) [custom_components.device_tracker.gplus] Google didn't send the location. Updating data['at']

**Expected:**

A new device_tracker pops up in the ui.

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml

device_tracker 1:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    waypoint_whitelist:
      - emiel   
  - platform: gplus
    id: emiel_android
    url: https://plus.google.com/u/0/_/PlusAppUi/data?ds.extension=**3**3**&f.sid=-**0***4***4***1****&hl=nl&soc-app=***&soc-platform=1&soc-device=1&_reqid=*****5&rt=c
    cookie_sid: '*****************************_*****************************************'
    cookie_hsid: '*****************'
    cookie_ssid: '*****************'
    data_freq: 15
    home_url: https://plus.google.com/u/0/{id_Main}

```

1. Boot Home-Assistant
2. Look at the log 

**Additional info:**

- Home-Assistant is running in a docker

- I Am using the "Safe Mode"
